### ISSUE TITLE
Coverity no longer accepts reports from CentOS7 containers because the coverity version is too old

### ISSUE THREAD

**Issue by tmadlener** [AIDASoft/management#6]
This is potentially related to #5. Should simply switching a coverity workflow to use an `el9` based LCG release work?

**Comment by andresailer** [comment]
I already changed that 16f38a9f90731b1476b715911625a4ba128a455d ? (I don't even remember...)

**Comment by andresailer** [comment]
Yes, switching the workflows to use the el9 instead of `latest` tag for the container should be it.

**Comment by tmadlener** [comment]
Not quite yet it seems: https://github.com/AIDASoft/podio/actions/runs/7246402281/job/19738267861#step:4:124

I am not entirely sure why though, because `readline-devel` should be in the installed packages for the `e9` image: 
https://github.com/AIDASoft/management/blob/16f38a9f90731b1476b715911625a4ba128a455d/el9/packages.txt#L39

**Comment by andresailer** [comment]
It still used the `latest` container instead of el9

**Comment by tmadlener** [comment]
So, do we push the `el9` based coverity container to `latest`, or should I explicitly ask for `coverity:el9` as container in the workflow (that I have to touch in any case to update the LCG release to an el9 based one)?

**Comment by andresailer** [comment]
Now that the centos7 coverity build silently fails, we might as well push el9 to latest.

**Comment by andresailer** [comment]
`latest` now points to `el9`

**Comment by tmadlener** [comment]
And at least podio has working coverity scans again :)
